#%RAML 1.0 NamedExample
  {
    number: "15713379317",
    valid: true,
    format: {
        local: "5713379317",
        international: "+15713379317"
    },
    country: {
        prefix: "+1",
        code: "US",
        name: "United States of America"
    },
    location: "Wsngtnzn17",
    carrier: "T-Mobile USA Inc.",
    line_type: "mobile",
    validationDate: "11 Jul, 2021",
    validationTime: "05:39:03 PM"
  }