#%RAML 1.0 DataType
type: array
items:
  type: object
  properties:
    phoneNumber: string
    id: integer
    fullName: null
    muleTimeStamp: string
    email: null
example: !include ../examples/customers-example.raml 
 
